services:
  db:
    image: postgres:16-alpine
    container_name: pg16
    hostname: pg16alpine
    environment:
      POSTGRES_USER: equipefoda
      POSTGRES_PASSWORD: equipefoda
    ports:
      - 45432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data


volumes:
  pg-data:
    name: pg-data
