services:
  projetodw:
    image: postgres:16-alpine
    container_name: projetodw
    hostname: pg16alpine
    environment:
      DBPOSTGRES: projetodw
      POSTGRES_USER: equipefoda
      POSTGRES_PASSWORD: "equipefoda"
    ports:
      - 55432:5432
    volumes:
      - ./projetodw/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./projetodw/projetodw-full.sql:/tmp/projetodw-full.sql
    networks:
      - projetodw_bd3

networks:
  projetodw_bd3:
    name: "projetodw_bd3"
